//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerOrdersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTypes
    {
        public int MaterialTypeID { get; set; }
        public string MaterialTypeName { get; set; }
        public decimal DefectPercentage { get; set; }
    }
}
