//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerOrdersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int OrderID { get; set; }
        public int PartnerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public bool PrepaymentReceived { get; set; }
        public Nullable<System.DateTime> PrepaymentDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Partners Partners { get; set; }
    }
}
