//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerOrdersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.Orders = new HashSet<Orders>();
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int PartnerID { get; set; }
        public int PartnerTypeID { get; set; }
        public string PartnerName { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LegalAddress { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual PartnerTypes PartnerTypes { get; set; }
    }
}
