//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerOrdersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypes
    {
        public ProductTypes()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ProductTypeID { get; set; }
        public string TypeName { get; set; }
        public decimal TypeCoefficient { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
