//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerOrdersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int ProductID { get; set; }
        public int ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public string Article { get; set; }
        public decimal MinPartnerPrice { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
